apiVersion: v1
kind: ConfigMap
metadata:
  name: azureopenai-config
data:
  title: "Azure OpenAI App running in Azure Red Hat OpenShift"
  description: "Azure OpenAI App running in Azure Red Hat OpenShift"
  port: "8080"
  deployment_name: "gpt-35-turbo"
  api_type: "azure"
  api_version: "2023-05-15"
