apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: aro-azureopenai
  name: aro-azureopenai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aro-azureopenai
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: aro-azureopenai
    spec:
      containers:
        - image: quay.io/rcarrata/aro-azureopenai:v3
          name: aro-azureopenai
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 15
          env: # Add this section to pass ConfigMap values as environment variables
            - name: title
              valueFrom:
                configMapKeyRef:
                  name: azureopenai-config
                  key: title
            - name: description
              valueFrom:
                configMapKeyRef:
                  name: azureopenai-config
                  key: description
            - name: port
              valueFrom:
                configMapKeyRef:
                  name: azureopenai-config
                  key: port
            - name: deployment_name
              valueFrom:
                configMapKeyRef:
                  name: azureopenai-config
                  key: deployment_name
            - name: api_type
              valueFrom:
                configMapKeyRef:
                  name: azureopenai-config
                  key: api_type
            - name: api_version
              valueFrom:
                configMapKeyRef:
                  name: azureopenai-config
                  key: api_version
            - name: OPENAI_API_BASE
              valueFrom:
                secretKeyRef:
                  name: azure-openai
                  key: OPENAI_API_BASE
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: azure-openai
                  key: OPENAI_API_KEY
